version: "3.7"
services:
  ruby-2-6: &ruby
    build:
      context: .
      args:
        RUBY_VERSION: 2.6.0
    volumes:
      - vendor:/vendor
    working_dir: /app
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
  ruby-2-5:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_VERSION: 2.5.3
  ruby-2-4:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_VERSION: 2.4.5
  mongo:
    image: mongo:3.2
    command: --storageEngine mmapv1
    volumes:
      - mongo-data:/data/db
volumes:
  home:
  vendor:
  mongo-data:
